@extends('default')
@section('content')
	<div class="wrapper style2">
		<div class="title">Conditions générales</div>
			<div id="highlights" class="container">
				<strong>Conditions Générales</strong> - Copyright© 2009 - <strong> VivaLaFiesta.ch</strong> 1er janvier 2009<h3>Préambule </h3>
				<p>Les Conditions générales ci-dessous régissent les rapports contractuels entre le Membre agréé et l'association VivaLaFiesta.ch.  Le Membre pourra consulter les Conditions générales de VivaLaFiesta.ch à tout moment par le biais du lien "Conditions générales" disponible au bas du site Internet VivaLaFiesta.ch, les imprimer ou les télécharger.</p> <h2>Objet des Conditions Générales </h2><h3>Modalité d'usage</h3>
				<p>Le site Internet VivaLaFiesta.ch propose une seule modalité d'usage au Membres inscrits : une inscription obligatoire donnant accès aux différentes prestations de VivaLaFiesta.ch. Disponibilité du site Internet Inscription du Membre</p>
				<h3>Inscription</h3>
				<p>L'accès aux prestations nécessite l'inscription au site Internet VivaLaFiesta.ch au moyen du formulaire "s'inscrire".</p>
				<h3>Données du Membre </h3>
				<p>Le Membre garantit la véracité de toutes les données fournies lors de l'inscription. Le Membre s'engage à transmettre immédiatement tout changement de coordonnées à VivaLaFiesta.ch dans l'onglet Mon compte/Mes informations afin de les actualiser, corriger ou compléter. L'usage de pseudonymes ou de noms d'artistes n'est pas admis.  </p><h3>Enregistrement unique </h3>
				<p>Le Membre ne peut s'enregistrer qu'une seule fois.  </p><h3>Limite d'âge du Membre </h3>
				<p>Majorité obligatoire, l'offre des prestations de VivaLaFiesta.ch est conseillée aux personnes de 30 ans et plus.  </p><h3>Identité des Membres </h3>
				<p>VivaLaFiesta.ch ne dispose pas de moyens techniques pour offrir une quelconque garantie quant à la véritable identité de ses Membres.  </p><h3>Acceptation de VivaLaFiesta.ch </h3>
				<p>Pour être un Membre agréé, ce dernier doit être accepté par l'association. VivaLaFiesta.ch se réserve le droit de refuser l'inscription d'un membre sans avoir à motiver sa décision.  </p><h3>Droit de révocation </h3>
				<p>Le Membre peut révoquer par courrier électronique son inscription à VivaLaFiesta.ch en tout temps sans avoir à motiver sa décision.   </p><h3>Sécurité du compte et mot de passe </h3>
				<p> </p><h3>Choix du mot de passe </h3>
				<p>Le Membre choisi son mot de passe au moment de l'inscription. Il est tenu de le maintenir secret. VivaLaFiesta.ch ne peut avoir connaissance du mot de passe de ses Membres.  </p><h3>Responsabilité du compte </h3>
				<p>Par conséquent, le Membre reconnait être le seul et unique responsable à l’égard de VivaLaFiesta.ch de tous actes effectués à partir de son compte.  </p><h3>Perte de mot de passe </h3>
				<p>En cas de perte du mot de passe, le membre peut se diriger vers le site Internet VivaLaFiesta.ch, dans la partie "s'identifier" et cliquer sur "mot de passe oublié". Un nouveau mot de passe lui sera automatiquement envoyé sur son adresse e-mail.   </p><h3>Données personnelles </h3>
				<p> </p><h3>Données visibles </h3>
				<p>Seuls la photo et le prénom du Membre seront visibles et ce, uniquement par les autres Membres agréés de VivaLaFiesta.ch. Toutes autres données transmises à l'association ne seront utilisées qu'à l'interne et ne pourront en aucun cas être utilisées à d'autres fins.  </p><h3>Protection des données </h3>
				<p>VivaLaFiesta.ch respecte toutes les règlementations en matière de protection des données. VivaLaFiesta.ch ne transmettra ni ne mettra à disposition d'autrui des données relatives aux données personnelles des membres sans autorisation préalable.   </p><h3>Obligations du Membre </h3>
				<p> </p><h3>Le Membre est tenu : </h3>
				<p>• De ne transmettre à VivaLaFiesta.ch que des photos de sa personne datées de cinq (5) ans maximum et permettant de clairement le reconnaître. Il est interdit de communiquer des photos ou des images d'autrui ou d'autres êtres (animaux, êtres fantastiques, logo d'entreprises, etc.). </p><h3>Le Membre reconnait qu'il est interdit de : </h3>
				<p>• Distribuer ou diffuser publiquement le contenu du site Internet VivaLaFiesta.ch ou ceux d'autres Membres. • D'effectuer toute action susceptible de porter préjudice à la fonctionnalité de l'infrastructure de VivaLaFiesta.ch, notamment de la surcharger. • de porter atteinte aux membres et à leur réputation ainsi qu'à celle de l'association VivaLaFiesta.ch, en diffusant ou colportant des informations relatives à ces derniers.</p><h3>Utilisation des prestations </h3>
				<p>• Le Membre accepte d'utiliser les prestations qu'aux seules fins autorisées (par les conditions, de la loi). • Le Membre accepte de ne pas avoir accès à toutes ou parties des prestations. • Le Membre accepte de n'entreprendre aucune activité de nature à entraver ou à perturber les prestations. • Le Membre reconnait être le seul et unique responsable de toute violation de ses obligations prévues aux Conditions générales et des conséquences (y compris toute perte ou tout préjudice subi par VivaLaFiesta.ch) d'une telle violation. Il reconnait expressément que VivaLaFiesta.ch ne saurait être responsable envers lui ou des tiers à cet égard .  </p><h3>Les activités VivaLaFiesta.ch </h3>
				<p> </p><h3>Nombre d'activités annuelles </h3>
				<p>Les évènements sont programmés par VivaLaFiesta.ch. Seul le comité d'organisation détermine la fréquence des évènements annuels.  </p><h3>Nombre d'entrées </h3>
				<p>Les évènements sont limités au nombre de places disponibles dans la salle. Le Membre accepte qu'il est possible qu'une activité soit complète et que l'association refuse l'inscription. Le nombre de places restantes est indiqué sur le compte à rebours de chaque évènement, sur le site Internet. Les inscriptions seront prises dans l'ordre d'arrivée. Aucun dédommagement ne pourra être exigé auprès de VivaLaFiesta.ch en cas de refus d'inscription.  </p><h3>Inscription aux activités et billets d'entrée </h3>
				<p>Pour chaque activité proposée par VivaLaFiesta.ch, une inscription est obligatoire ainsi que le paiement en ligne et par avance d'un billet d'entrée. Le prix d'entrée de chaque activité est déterminé par VivaLaFiesta.ch et dépend des diverses prestations offertes lors de cette soirée (le détail des prestations pour chaque activité est disponible sur le site Internet).  </p><h3>Désinscription aux activités </h3>
				<p>Les Membres ont la possibilité de se désister sans avoir l'obligation de motiver leur décision, au plus tard 15 jours avant l'activité. Ainsi, ils seront remboursés. Passé ce délai, les Membres désinscrits ne pourront plus exiger le remboursement de leur billet sauf pour des raisons de force majeur.  </p><h3>Participants aux activités </h3>
				<p>Seuls les Membres agréés de VivaLaFiesta.ch ont la possibilité de s'inscrire et de participer, sur présentation d'une carte d'identité, aux différentes activités privées proposées par l'association.  </p><h3>Annulation d'une activité</h3>
				<p>VivaLaFiesta.ch se réserve le droit d'annuler, en tout temps, une activité lorsque le nombre de participants n'est pas suffisant. Tous les Membres inscrits seront avertis par e-mail ou SMS et seront entièrement remboursés en remplissant le formulaire de contact de VivaLaFiesta.ch.  </p><h3>Moyen de diffusion et d'information </h3>
				<p>VivaLaFiesta.ch contacte ses Membres par SMS sur les téléphones portables, par email et les informe grâce à une newsletter. Ces prestations seront utilisées aux seules fin d'information quant à une activité à laquelle le Membre est inscrit ou à venir et leur fréquence sera limitée. Les numéros de téléphones portables ou adresse e-mail des Membres ne seront en aucun cas utilisés pour l'envoi de quelconques publicités ou autres spams. La prestation de Newsletter et de SMS est entièrement gratuite. </p><h3>Responsabilité de VivaLaFiesta.ch </h3>
				<p> </p><h3>Quant aux données des Membres </h3>
				<p>VivaLaFiesta.ch décline toute responsabilité quant au contenu des données et des informations fournies par les Membres VivaLaFiesta.ch.  </p><h3>Quant aux dégâts lors d'activités </h3>
				<p>VivaLaFiesta.ch décline toute responsabilité en cas d'accident, de perte, de vol, ou de quelconques dégâts ayant lieu lors d'une activité de VivaLaFiesta.ch.  </p><h3>Dommages et intérêts </h3>
				<p>Aucune demande en dommages et intérêts à l'encontre de VivaLaFiesta.ch ne pourra être formulée. </p><h3>Modifications des prestations VivaLaFiesta.ch </h3>
				<p>VivaLaFiesta.ch se réserve le droit de modifier les prestations proposées sur son site Internet, en tout temps et sans avoir à motiver ses choix, ou d'offrir d'autres prestations.  </p><h3>Résiliation de contrat </h3>
				<p> </p><h3>Résiliation du Membre </h3>
				<p>Le Membre a la possibilité de résilier son inscription par courrier électronique en tout temps sans avoir à motiver sa décision. Sans résiliation écrite du Membre, l'inscription sera reconduite tacitement pour une année. La résiliation est prise en compte pour l'année suivante.  </p><h3>Résiliation de VivaLaFiesta.ch </h3>
				<p>VivaLaFiesta.ch se réserve le droit de résilier le contrat de l'un ou plusieurs de ses Membres, en tout temps sans avoir à motiver sa décision. Les cas visés ici concernent notamment les circonstances empêchant la poursuite des rapports contractuels notamment : • Le non respect des dispositions légales ainsi que les conditions générales de la part du Membre. • Un comportement inadapté ou délacé du Membre lors d'une activité de l'association.Dans ces situations, le Membre n'a pas droit au remboursement des paiements effectués à l'avance. </p><h3>Prestations à la clientèle </h3>
				<p>Les Membres agréés peuvent en tout temps faire part de leurs remarques, questions ou suggestions au sujet des prestations de VivaLaFiesta.ch, ainsi que du contrat qui les lie à VivaLaFiesta.ch, au moyen du formulaire de contact ou en envoyant un courrier électronique à l'adresse suivante : info@vivalafiesta.ch. Il est, entre autre, possible de soumettre au comité d'organisation une proposition d'activité. Le comité se réserve le droit d'accepter ou de refuser les propositions sans avoir à motiver son choix. </p><h3>Disponibilité de l'information</h3>
				<p></p><h3> </h3>
				<p>Le membre admet qu'il est techniquement impossible d'assurer une disponibilité permanente du site Internet VivaLaFiesta.ch. VivaLaFiesta.ch veillera neanmoins à ce que son site Internet soit aussi disponible que possible. Il est probable que pour diverses raisons, l'accès au site Internet de VivaLaFiesta.ch soit momentanément perturbé ou suspendu. </p><h3>Soutien à VivaLaFiesta.ch </h3>
				<p>Toute personne souhaitant soutenir l'association VivaLaFiesta.ch a la possibilité d'envoyer un don au CCP suivant: VivaLaFiesta.ch N°10-742862-5 ou en prenant contact par e-mail à l'adresse suivante : info@vivalafiesta.ch</p><h3>Statuts de VivaLaFiesta.ch</h3>
				<p>VivaLaFiesta.ch étant une Association au sens du droit suisse, les statuts la régissant font partie intégrante des Conditions Générales. Les statuts peuvent être consultés en écrivant à info@vivalafiesta.ch </p><h3>Acceptation des CG</h3>
				<p></p><h3> </h3>
				<p>L'inscription en tant que membre de VivaLaFiesta.ch implique l'acceptation des Conditions générales en vigueur de VivaLaFiesta.ch.  </p><h3>Modifications des Conditions Générales </h3>
				<p> </p><h3>Modifications</h3>
				<p>VivaLaFiesta.ch se réserve le droit de modifier en tout temps les présentes Conditions Générales sans justification préalable. Dans cette hypothèse, VivaLaFiesta.ch mettra les Conditions Générales modifiées à la disposition de ses Membres.  </p><h3>Dispositions finales </h3>
				<p> </p><h3>Siège de VivaLaFiesta </h3>
				<p>Le lieu d'exécution est le siège de VivaLaFiesta.ch. Le siège de l'association se situe à Neuchâtel.  </p><h3>Compétence judiciaire </h3>
				<p>Dans le cas où des différends résultant du présent contrat ou en relation avec lui ne pourraient pas être réglés par la voie d’un accord amiable, les parties font élection de for exclusif à Neuchâtel.</p><h3>Législation applicable </h3>
				<p>La législation applicable est la législation suisse.</p>
			</div>
		</div>
@stop